server:
  port: 19003
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1 #最大工作线程数量
    min-spare-threads: 1 #最小工作线程数量
    #max-connections: 10000 #一瞬间最大支持的并发的连接数
    accept-count: 1 #等待队列长度

spring:
  application:
    name: java-study
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true #是否检查模板位置是否存在
    suffix: .html
    encoding: utf-8 #模板编码
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false #禁用缓存，本地开发设置为false，避免修改后重启服务器

jlpay:
  framework:
    work:
      request:
        threadpool:
          corePoolSize: 18
          keepAliveSeconds: 100
          maxPoolSize: 50
          queueCapacity: 100
          threadNamePrefix: busi-req-
      response:
        threadpool:
          corePoolSize: 18
          keepAliveSeconds: 100
          maxPoolSize: 50
          queueCapacity: 100
          threadNamePrefix: busi-resp-
    asyn-http:
      connectTimeout: 5000
      maxConnPerRoute: 1000
      maxConnTotal: 1000
      readTimeout: 30000
      threadCount: 15
      threadpool:
        corePoolSize: 5
        keepAliveSeconds: 60
        maxPoolSize: 15
        queueCapacity: 1000
        threadNamePrefix: http-response-${server.port}-pool-

ws:
  port: 8087
test:
  enable: true


http:
  connection:
    request:
      timeout: 50000
    timeout: 10000
  socket:
    connection:
      timeout: 15000

